
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 3.02
//   File : Messages_types.cpp
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

#include "Messages_reflection.h"
#include <bond/core/exception.h>

namespace Message
{
    
    const bond::Metadata Request::Schema::metadata
        = Request::Schema::GetMetadata();
    
    const bond::Metadata Request::Schema::s_keyword_metadata
        = bond::reflection::MetadataInit("keyword");

    
    const bond::Metadata Response::Schema::metadata
        = Response::Schema::GetMetadata();
    
    const bond::Metadata Response::Schema::s_matches_metadata
        = bond::reflection::MetadataInit("matches");

    
} // namespace Message
